In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [2]:
valid_guesses_csv = pd.read_csv("valid_guesses.csv")
valid_solutions_csv = pd.read_csv("valid_solutions.csv")
valid_guesses_csv = valid_guesses_csv.merge(valid_solutions_csv, how='outer')

In [3]:
data = pd.read_excel("COCA60000FULL.xlsx")
data["word"] = data["word"].str.replace(' ', '')

data

,RANK #,PoS,word,TOTAL,SPOKEN,FICTION,MAGAZINE,NEWSPAPER,ACADEMIC
0,1,A,the,23782115,4183469,4531786,4875815,4646517,5544528
1,2,V,be,16711569,4873288,3173845,2989059,2926800,2748577
2,3,C,and,11654439,2347151,2188166,2388111,2130798,2600213
3,4,I,of,11155504,1857279,1630728,2329089,2050072,3288336
4,5,A,a,10999596,2110287,2125067,2496150,2331699,1936393
...,...,...,...,...,...,...,...,...,...
60018,60020,N,hecatomb,20,0,2,2,0,16
60019,60021,N,sideslip,19,0,16,3,0,0
60020,60022,N,gaoler,23,0,1,0,0,22
60021,60023,N,carcinoid,21,0,0,0,0,21
60022,60024,N,tonus,21,0,1,2,0,18

In [4]:
data_selected = data[data["word"].str.len() == 5]
data_selected = data_selected.sort_values(by="TOTAL", axis=0, ascending=True)
data_selected["weight"] = data_selected["TOTAL"] / data_selected["TOTAL"].sum()
data_selected

,RANK #,PoS,word,TOTAL,SPOKEN,FICTION,MAGAZINE,NEWSPAPER,ACADEMIC,weight
57873,57875,J,unhip,18,0,7,4,6,1,4.164350e-07
59267,59269,R,roily,19,0,11,7,0,1,4.395703e-07
58747,58749,J,topsy,19,4,10,2,1,2,4.395703e-07
58806,58808,N,shoat,19,0,14,2,2,1,4.395703e-07
58818,58820,J,homed,19,0,10,4,0,5,4.395703e-07
...,...,...,...,...,...,...,...,...,...,...
55,56,V,think,838695,423892,193081,88312,93525,39885,1.940344e-02
52,53,E,there,846483,301556,155571,135904,139865,113587,1.958362e-02
45,46,I,about,952604,328762,178533,163092,163636,118581,2.203876e-02
40,41,V,would,1000182,251284,257792,166384,178690,146032,2.313949e-02
35,36,A,their,1170105,184917,176141,250636,232098,326313,2.707070e-02

In [5]:
valid_guesses_inner = valid_guesses_csv.merge(data_selected, how='inner', on='word')
valid_guesses_inner = valid_guesses_inner[ valid_guesses_inner["weight"] >= 0.000000001 ]
valid_guesses_inner = valid_guesses_inner.reset_index()
valid_guesses_inner

,index,word,RANK #,PoS,TOTAL,SPOKEN,FICTION,MAGAZINE,NEWSPAPER,ACADEMIC,weight
0,0,abash,49621,V,32,7,12,6,3,4,7.403288e-07
1,1,abaya,43717,N,69,12,12,14,24,7,1.596334e-06
2,2,ackee,58672,N,29,0,10,13,3,3,6.709230e-07
3,3,actin,31873,N,148,8,45,32,0,63,3.424021e-06
4,4,added,4592,J,6047,449,462,2121,1734,1281,1.398990e-04
...,...,...,...,...,...,...,...,...,...,...,...
3946,3946,young,234,J,173683,31095,42319,34792,36717,28760,4.018204e-03
3947,3947,youth,1401,N,31288,2434,3196,4907,7636,13115,7.238565e-04
3948,3948,zebra,14397,N,1148,110,242,445,136,215,2.655930e-05
3949,3949,zesty,28061,J,211,6,11,129,63,2,4.881543e-06
3950,3950,zonal,41500,J,66,1,1,17,2,45,1.526928e-06

In [6]:
valid_solutions_inner = valid_solutions_csv.merge(data_selected, how='inner', on='word')
valid_solutions_inner = valid_solutions_inner[ valid_solutions_inner["weight"] >= 0.0004 ]
valid_solutions_inner = valid_solutions_inner.reset_index()
valid_solutions_inner

,index,word,RANK #,PoS,TOTAL,SPOKEN,FICTION,MAGAZINE,NEWSPAPER,ACADEMIC,weight
0,8,about,179,R,226187,56650,33118,57435,54485,24499,0.005233
1,9,about,46,I,952604,328762,178533,163092,163636,118581,0.022039
2,11,above,1595,R,25231,821,3498,10410,2163,8339,0.000584
3,12,above,894,I,47550,3965,16189,12222,6849,8325,0.001100
4,14,abuse,1545,N,26768,6019,764,5086,5387,9512,0.000619
...,...,...,...,...,...,...,...,...,...,...,...
398,2960,would,41,V,1000182,251284,257792,166384,178690,146032,0.023139
399,2973,write,228,V,176548,35949,27278,37680,35245,40396,0.004084
400,2977,wrong,655,J,63810,21611,17297,10356,9579,4967,0.001476
401,2984,young,234,J,173683,31095,42319,34792,36717,28760,0.004018
402,2985,youth,1401,N,31288,2434,3196,4907,7636,13115,0.000724

In [26]:
valid_guesses = valid_guesses_inner["word"].tolist()
valid_solutions = valid_solutions_inner["word"].tolist()

valid_guesses.append("eerie")
valid_solutions.append("eerie")

valid_guesses = list( set(valid_guesses) )
valid_solutions = list( set(valid_solutions) )
valid_guesses = sorted(valid_guesses)
valid_solutions = sorted(valid_solutions)

valid_guesses_cnt = len(valid_guesses)
valid_solutions_cnt = len(valid_solutions)

# print(valid_guesses)
# print(valid_solutions)
# print(valid_guesses_cnt)
# print(valid_solutions_cnt)

['aback', 'abase', 'abash', 'abate', 'abaya', 'abbot', 'abhor', 'abide', 'abode', 'abort', 'about', 'above', 'abuse', 'abyss', 'ackee', 'acorn', 'acrid', 'actin', 'actor', 'acute', 'adage', 'adapt', 'added', 'adder', 'addle', 'adept', 'adieu', 'adios', 'adman', 'admin', 'admit', 'adobe', 'adobo', 'adopt', 'adore', 'adorn', 'adult', 'aegis', 'aerie', 'affix', 'afire', 'afoot', 'afore', 'after', 'again', 'agape', 'agave', 'agent', 'aggro', 'agile', 'aging', 'aglow', 'agony', 'agora', 'agree', 'ahead', 'ahold', 'aided', 'aioli', 'aired', 'aisle', 'alarm', 'album', 'alder', 'alert', 'algae', 'algal', 'alias', 'alibi', 'alien', 'align', 'alike', 'alive', 'alkyd', 'allay', 'alley', 'allot', 'allow', 'alloy', 'aloft', 'alone', 'along', 'aloof', 'aloud', 'alpha', 'altar', 'alter', 'amass', 'amaze', 'amber', 'ambit', 'amble', 'amend', 'amine', 'amino', 'amiss', 'amity', 'amnio', 'among', 'amour', 'ample', 'amply', 'amuse', 'ancho', 'angel', 'anger', 'angle', 'anglo', 'angry', 'angst', 'anima', 'anime', 'anion', 'anise', 'ankle', 'annal', 'annex', 'annoy', 'annul', 'anode', 'anole', 'antic', 'antsy', 'anvil', 'aorta', 'apace', 'apart', 'aphid', 'apnea', 'apple', 'apply', 'apron', 'aptly', 'ardor', 'areal', 'arena', 'argon', 'argot', 'argue', 'arise', 'armed', 'armor', 'aroma', 'array', 'arrow', 'arson', 'artsy', 'ashen', 'aside', 'askew', 'aspic', 'assay', 'asset', 'aster', 'astir', 'atman', 'atoll', 'atone', 'attar', 'attic', 'audio', 'audit', 'auger', 'aught', 'augur', 'aunty', 'aural', 'avail', 'avert', 'avian', 'avoid', 'await', 'awake', 'award', 'aware', 'awash', 'awful', 'axial', 'axiom', 'axion', 'azure', 'bacon', 'badge', 'badly', 'bagel', 'baggy', 'bairn', 'baize', 'baked', 'baker', 'baled', 'balky', 'balmy', 'balsa', 'banal', 'bandy', 'banjo', 'bared', 'barge', 'basal', 'basic', 'basil', 'basin', 'basis', 'basso', 'baste', 'batch', 'bated', 'bathe', 'batik', 'batty', 'bawdy', 'bazar', 'beach', 'beady', 'beaky', 'beamy', 'beard', 'beast', 'beaut', 'bebop', 'beefy', 'beery', 'befit', 'beget', 'begin', 'begum', 'beige', 'being', 'belay', 'belch', 'belie', 'belly', 'below', 'bench', 'benne', 'beret', 'berry', 'berth', 'beset', 'betel', 'bevel', 'bezel', 'bible', 'bidet', 'bight', 'bigot', 'biker', 'bilge', 'bimbo', 'binge', 'bingo', 'biome', 'biota', 'biped', 'bipod', 'birch', 'birth', 'bison', 'bitch', 'biter', 'bitty', 'black', 'blade', 'blahs', 'blame', 'bland', 'blank', 'blare', 'blase', 'blast', 'blaze', 'bleak', 'bleat', 'bleed', 'bleep', 'blend', 'bless', 'blimp', 'blind', 'bling', 'blini', 'blink', 'bliss', 'blitz', 'bloat', 'block', 'bloke', 'blond', 'blood', 'bloom', 'bloop', 'blown', 'blued', 'bluff', 'blunt', 'blurb', 'blurt', 'blush', 'board', 'boast', 'bocce', 'boeuf', 'boffo', 'bogey', 'boggy', 'bogus', 'bolus', 'boned', 'boner', 'boney', 'bonny', 'bonus', 'booby', 'boost', 'booth', 'booty', 'booze', 'boozy', 'borax', 'bored', 'borer', 'boric', 'boron', 'bosom', 'boson', 'bossy', 'bosun', 'botch', 'bough', 'boule', 'bound', 'bowed', 'bowel', 'boxed', 'boxer', 'boyar', 'brace', 'bract', 'braid', 'brain', 'brake', 'brand', 'brane', 'brash', 'brass', 'brave', 'brawl', 'brawn', 'braze', 'bread', 'break', 'bream', 'breed', 'briar', 'bribe', 'brick', 'bride', 'brief', 'brier', 'brine', 'bring', 'brink', 'briny', 'brisk', 'broad', 'broil', 'broke', 'bronc', 'brood', 'brook', 'broom', 'broth', 'brown', 'bruit', 'brunt', 'brush', 'brute', 'bucko', 'buddy', 'budge', 'buggy', 'bugle', 'build', 'bulge', 'bulky', 'bully', 'bumpy', 'bunch', 'bunco', 'bunny', 'burin', 'burka', 'burly', 'burnt', 'burro', 'burst', 'bushy', 'busty', 'butch', 'buxom', 'buyer', 'buzzy', 'bylaw', 'byway', 'cabal', 'cabby', 'caber', 'cabin', 'cable', 'cacao', 'cache', 'caddy', 'cadet', 'cadge', 'cadre', 'caged', 'cagey', 'cairn', 'calla', 'calve', 'calyx', 'camel', 'cameo', 'campy', 'canal', 'candy', 'caned', 'canid', 'canna', 'canny', 'canoe', 'canon', 'canst', 'canto', 'caped', 'caper', 'capon', 'carat', 'cargo', 'carny', 'carob', 'carol', 'carom', 'carry', 'carte', 'carve', 'cased', 'caste', 'catch', 'cater', 'catty', 'caulk', 'cause', 'cavil', 'cease', 'cedar', 'ceded', 'celeb', 'cello', 'chafe', 'chaff', 'chain', 'chair', 'chalk', 'champ', 'chant', 'chaos', 'chard', 'charm', 'chart', 'chary', 'chase', 'chasm', 'cheap', 'cheat', 'check', 'cheek', 'cheep', 'cheer', 'chemo', 'chert', 'chess', 'chest', 'chewy', 'chick', 'chide', 'chief', 'child', 'chili', 'chill', 'chime', 'chimp', 'chine', 'chink', 'chino', 'chirp', 'chock', 'choir', 'choke', 'chomp', 'chord', 'chore', 'chuck', 'chuff', 'chump', 'chunk', 'churn', 'chute', 'cider', 'cigar', 'cinch', 'cited', 'civet', 'civic', 'civil', 'civvy', 'clack', 'clade', 'claim', 'clamp', 'clang', 'clank', 'claro', 'clash', 'clasp', 'class', 'clave', 'clean', 'clear', 'cleat', 'cleft', 'clerk', 'click', 'cliff', 'climb', 'clime', 'cling', 'clink', 'cloak', 'clock', 'clomp', 'clone', 'close', 'cloth', 'cloud', 'clout', 'clove', 'clown', 'cloze', 'cluck', 'clump', 'clunk', 'coach', 'coast', 'cobia', 'cocky', 'cocoa', 'codec', 'coded', 'coder', 'codex', 'codon', 'colic', 'colon', 'color', 'comal', 'combo', 'comer', 'comet', 'comfy', 'comic', 'comma', 'commo', 'conch', 'condo', 'conga', 'conic', 'copal', 'copra', 'copse', 'coral', 'corgi', 'corky', 'corny', 'corps', 'cotta', 'couch', 'cough', 'could', 'count', 'coupe', 'court', 'coven', 'cover', 'covet', 'cowed', 'cower', 'cowry', 'coyly', 'crack', 'craft', 'cramp', 'crane', 'crank', 'crape', 'crash', 'crass', 'crate', 'crave', 'crawl', 'craze', 'crazy', 'creak', 'cream', 'credo', 'creed', 'creep', 'creme', 'crepe', 'cress', 'crest', 'crime', 'crimp', 'crisp', 'croak', 'crock', 'crone', 'crony', 'crook', 'croon', 'cross', 'croup', 'crowd', 'crown', 'crude', 'cruel', 'cruet', 'crumb', 'crush', 'crust', 'crypt', 'cubby', 'cubic', 'cubit', 'cuddy', 'cumin', 'cupid', 'cuppa', 'cured', 'curia', 'curio', 'curly', 'curry', 'curse', 'curve', 'curvy', 'cushy', 'cutie', 'cycad', 'cycle', 'cyclo', 'cynic', 'dacha', 'daffy', 'daily', 'dairy', 'dally', 'damar', 'dance', 'dandy', 'darky', 'dashi', 'dated', 'datum', 'daunt', 'davit', 'dazed', 'deary', 'death', 'debit', 'debug', 'debut', 'decaf', 'decal', 'decay', 'decor', 'decoy', 'decry', 'defer', 'deify', 'deign', 'deism', 'deist', 'deity', 'delay', 'delft', 'delve', 'demon', 'demur', 'denim', 'dense', 'depth', 'deter', 'detox', 'deuce', 'devil', 'dhoti', 'diary', 'diced', 'dicey', 'digit', 'dildo', 'dimer', 'dimly', 'dinar', 'diner', 'dingy', 'dinky', 'diode', 'dippy', 'dirge', 'dirty', 'disco', 'dishy', 'ditch', 'ditsy', 'ditty', 'ditzy', 'divan', 'diver', 'divot', 'divvy', 'dizzy', 'dodge', 'dodgy', 'doggy', 'dogma', 'dolor', 'domed', 'donor', 'donut', 'doozy', 'dopey', 'doric', 'dorky', 'dosed', 'dotty', 'doubt', 'dough', 'doula', 'douse', 'dowdy', 'dowel', 'downy', 'dowry', 'dowse', 'doyen', 'dozen', 'dozer', 'draft', 'drain', 'drama', 'drape', 'drawl', 'dread', 'dream', 'dreck', 'dregs', 'dress', 'dried', 'drier', 'drift', 'drill', 'drily', 'drink', 'drive', 'droid', 'droit', 'droll', 'drone', 'drool', 'droop', 'dross', 'drove', 'drown', 'drunk', 'dryer', 'dryly', 'ducal', 'ducat', 'duchy', 'ducky', 'dully', 'dummy', 'dumpy', 'dunce', 'duomo', 'duped', 'dural', 'durum', 'dusky', 'dusty', 'dutch', 'duvet', 'dwarf', 'dweeb', 'dwell', 'dying', 'eager', 'eagle', 'eared', 'early', 'easel', 'eater', 'eclat', 'edema', 'edged', 'edict', 'edify', 'eejit', 'eerie', 'egret', 'eider', 'eight', 'eject', 'ejido', 'elate', 'elbow', 'elder', 'elect', 'elegy', 'elide', 'elite', 'elope', 'elude', 'elven', 'embed', 'ember', 'emcee', 'emend', 'emote', 'empty', 'enact', 'endow', 'enema', 'enemy', 'enjoy', 'ennui', 'enoki', 'ensue', 'enter', 'entry', 'envoy', 'eosin', 'epoch', 'epoxy', 'equal', 'equip', 'erase', 'erect', 'erode', 'error', 'erupt', 'essay', 'ether', 'ethic', 'ethos', 'ethyl', 'etude', 'evade', 'event', 'every', 'evict', 'evoke', 'exact', 'exalt', 'excel', 'exert', 'exile', 'exist', 'expat', 'expel', 'extol', 'extra', 'exude', 'exult', 'exurb', 'eyrie', 'fable', 'faced', 'facet', 'faded', 'faery', 'faggy', 'faint', 'fairy', 'faith', 'faked', 'faker', 'fakir', 'false', 'famed', 'fancy', 'fanny', 'farce', 'fatal', 'fated', 'fatso', 'fatty', 'fatwa', 'fault', 'fauna', 'favor', 'faxed', 'feast', 'fecal', 'feces', 'feign', 'feint', 'fella', 'felon', 'femur', 'fence', 'feral', 'ferry', 'fetal', 'fetch', 'fetid', 'fetus', 'fever', 'fewer', 'fiber', 'fibre', 'ficus', 'field', 'fiend', 'fiery', 'fifth', 'fifty', 'fight', 'filch', 'filer', 'filet', 'fille', 'filly', 'filmy', 'filth', 'final', 'finca', 'fined', 'fines', 'finis', 'finny', 'fiord', 'fired', 'first', 'fishy', 'fiver', 'fixed', 'fixer', 'fizzy', 'fjord', 'flack', 'flail', 'flair', 'flake', 'flaky', 'flame', 'flank', 'flare', 'flash', 'flask', 'fleck', 'fleet', 'flesh', 'flick', 'flier', 'fling', 'flirt', 'float', 'flock', 'flood', 'floor', 'floss', 'flour', 'flout', 'fluff', 'fluid', 'fluke', 'fluky', 'flume', 'flunk', 'flush', 'flute', 'flyby', 'flyer', 'foamy', 'focal', 'focus', 'fogey', 'foggy', 'foist', 'folic', 'folio', 'folky', 'folly', 'foray', 'force', 'forge', 'forgo', 'forme', 'forte', 'forth', 'forty', 'forum', 'fossa', 'found', 'fount', 'fovea', 'foyer', 'frail', 'frame', 'frank', 'fraud', 'freak', 'freed', 'fresh', 'friar', 'fried', 'frill', 'frisk', 'frizz', 'frock', 'frond', 'front', 'frosh', 'frost', 'froth', 'frown', 'fruit', 'fryer', 'fudge', 'fugal', 'fugue', 'fully', 'fungo', 'funky', 'funny', 'furor', 'furry', 'fused', 'fussy', 'fusty', 'futon', 'fuzzy', 'gabby', 'gaffe', 'gaily', 'gamer', 'gamma', 'gamut', 'ganja', 'gassy', 'gated', 'gaudy', 'gauge', 'gaunt', 'gauss', 'gauze', 'gauzy', 'gavel', 'gawky', 'gecko', 'geeky', 'gelid', 'genie', 'genre', 'genus', 'gesso', 'ghost', 'ghoul', 'giant', 'giddy', 'gimpy', 'girly', 'girth', 'given', 'giver', 'gizmo', 'glade', 'gland', 'glare', 'glass', 'glaze', 'gleam', 'glean', 'glial', 'glide', 'glint', 'glitz', 'gloat', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'glued', 'gluon', 'glute', 'glyph', 'gnash', 'gnome', 'godly', 'gofer', 'going', 'golem', 'golly', 'gonad', 'goner', 'goody', 'gooey', 'goofy', 'goopy', 'goose', 'gored', 'gorge', 'gorse', 'gouge', 'gourd', 'grace', 'grade', 'graft', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'graze', 'great', 'grebe', 'greed', 'greek', 'green', 'greet', 'grief', 'grill', 'grime', 'grimy', 'grind', 'griot', 'gripe', 'grist', 'groan', 'groin', 'groom', 'grope', 'gross', 'group', 'grout', 'growl', 'grown', 'gruel', 'gruff', 'grump', 'grunt', 'guano', 'guard', 'guava', 'guess', 'guest', 'guide', 'guile', 'guilt', 'guise', 'gulag', 'gully', 'gumbo', 'gummy', 'gunky', 'gunny', 'guppy', 'gushy', 'gusto', 'gusty', 'gutsy', 'gutta', 'gypsy', 'gyrus', 'habit', 'haiku', 'hairy', 'halal', 'hallo', 'halon', 'halve', 'hammy', 'handy', 'hanky', 'haole', 'happy', 'hardy', 'harem', 'harpy', 'harsh', 'haste', 'hasty', 'hatch', 'hated', 'hater', 'haunt', 'haven', 'havoc', 'hazel', 'heady', 'heart', 'heave', 'heavy', 'hedge', 'hefty', 'heist', 'helix', 'hello', 'hence', 'henna', 'heron', 'hijab', 'hijra', 'hiker', 'hilar', 'hilly', 'hinge', 'hinky', 'hippo', 'hired', 'hissy', 'hitch', 'hoard', 'hoary', 'hobby', 'hoist', 'hokey', 'hokum', 'holey', 'homed', 'homer', 'homey', 'homie', 'honey', 'honky', 'honor', 'hooch', 'hooey', 'hoppy', 'horde', 'horny', 'horse', 'horsy', 'hosel', 'hosta', 'hotel', 'hotly', 'hound', 'houri', 'house', 'hovel', 'hover', 'howdy', 'hubby', 'huffy', 'huggy', 'hullo', 'human', 'humic', 'humid', 'humor', 'humus', 'hunch', 'hunky', 'hurry', 'husky', 'hussy', 'hydro', 'hyena', 'hymen', 'hyoid', 'hyped', 'hyper', 'hyrax', 'ichor', 'icily', 'icing', 'ideal', 'idiom', 'idiot', 'idled', 'idler', 'idyll', 'igloo', 'iliac', 'ilium', 'image', 'imago', 'imbed', 'imbue', 'impel', 'imply', 'inane', 'inapt', 'incur', 'incus', 'index', 'indie', 'inept', 'inert', 'infer', 'infra', 'ingot', 'inked', 'inlay', 'inlet', 'inner', 'input', 'inset', 'inter', 'intro', 'inure', 'ionic', 'irate', 'irked', 'irony', 'islet', 'issue', 'itchy', 'ivory', 'jaded', 'jammy', 'jaunt', 'jazzy', 'jeans', 'jello', 'jelly', 'jerky', 'jetty', 'jewel', 'jiffy', 'jihad', 'jinks', 'joint', 'joist', 'joker', 'jokey', 'jolly', 'joust', 'jowly', 'judge', 'juice', 'juicy', 'julep', 'jumbo', 'jumpy', 'junky', 'junta', 'junto', 'jural', 'juror', 'kabob', 'kafir', 'kanji', 'kapok', 'kaput', 'karat', 'karma', 'karst', 'kasha', 'kayak', 'kazoo', 'kebab', 'kefir', 'kente', 'ketch', 'khaki', 'kicky', 'kiddo', 'kiddy', 'kilim', 'kinda', 'kinky', 'kiosk', 'kitty', 'klick', 'klutz', 'knack', 'knave', 'knead', 'kneel', 'knell', 'knife', 'knock', 'knoll', 'known', 'koala', 'kooky', 'kopje', 'krait', 'kraut', 'krill', 'kudos', 'kudzu', 'kugel', 'kulak', 'kurta', 'label', 'labor', 'laced', 'ladle', 'lager', 'laity', 'lanai', 'lanky', 'lapel', 'lapin', 'lapse', 'large', 'larva', 'laser', 'lasso', 'latch', 'later', 'latex', 'lathe', 'latke', 'latte', 'laugh', 'layer', 'layup', 'leach', 'leafy', 'leaky', 'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'leech', 'leery', 'legal', 'leggy', 'lehua', 'lemma', 'lemon', 'lemur', 'leper', 'levee', 'level', 'lever', 'liana', 'libel', 'lidar', 'liege', 'lifer', 'light', 'liked', 'liken', 'lilac', 'limbo', 'limey', 'limit', 'linac', 'lined', 'linen', 'liner', 'lingo', 'lipid', 'liter', 'lithe', 'liven', 'liver', 'livid', 'llama', 'loamy', 'loath', 'lobby', 'local', 'locus', 'loden', 'lodge', 'loess', 'lofty', 'logic', 'logon', 'lolly', 'loner', 'loony', 'loopy', 'loose', 'lorry', 'loser', 'lossy', 'lotto', 'loupe', 'louse', 'lousy', 'loved', 'lover', 'lower', 'lowly', 'loyal', 'lucid', 'lucky', 'lucre', 'ludic', 'luger', 'lumen', 'lumpy', 'lunar', 'lunch', 'lunge', 'lupus', 'lurch', 'lurid', 'lusty', 'lycee', 'lying', 'lymph', 'lynch', 'lyric', 'lysis', 'lytic', 'macaw', 'mache', 'macho', 'macro', 'madam', 'madly', 'magic', 'magma', 'magus', 'maize', 'major', 'maker', 'malty', 'mambo', 'manga', 'mange', 'mango', 'mangy', 'mania', 'manic', 'manly', 'manna', 'manse', 'manta', 'manus', 'maple', 'march', 'marry', 'marsh', 'maser', 'match', 'mated', 'mater', 'matey', 'maths', 'matte', 'matzo', 'mauve', 'maven', 'maxim', 'mayan', 'maybe', 'mayor', 'mealy', 'meaty', 'medal', 'media', 'medic', 'melee', 'melon', 'mercy', 'merge', 'merit', 'merry', 'mesic', 'meson', 'messy', 'metal', 'meter', 'metro', 'mezzo', 'micro', 'midge', 'midst', 'might', 'miler', 'milky', 'mimic', 'mince', 'mined', 'miner', 'minor', 'minty', 'minus', 'mired', 'mirin', 'mirth', 'miser', 'misty', 'miter', 'mitre', 'mixed', 'mixer', 'mocha', 'mochi', 'modal', 'model', 'modem', 'modus', 'mogul', 'moire', 'moist', 'molar', 'moldy', 'money', 'month', 'mooch', 'moody', 'moony', 'moose', 'moped', 'moral', 'moray', 'morel', 'moron', 'morph', 'mosey', 'mossy', 'motel', 'motet', 'motif', 'motor', 'motto', 'mould', 'mound', 'mount', 'mourn', 'mouse', 'mousy', 'mouth', 'moved', 'mover', 'movie', 'mowed', 'mower', 'moxie', 'mucin', 'mucky', 'mucus', 'muddy', 'mufti', 'muggy', 'mulch', 'muley', 'mummy', 'mumps', 'munch', 'mural', 'murky', 'murre', 'mushy', 'music', 'musky', 'musty', 'muted', 'muzzy', 'mylar', 'mynah', 'myrrh', 'nabob', 'nacho', 'nadir', 'naive', 'naked', 'named', 'nanny', 'nappy', 'narco', 'nasal', 'nasty', 'natal', 'natty', 'naval', 'navel', 'neath', 'needy', 'neigh', 'nerdy', 'nerve', 'nervy', 'never', 'newel', 'newly', 'newsy', 'nexus', 'ngoma', 'nicad', 'niche', 'niece', 'nifty', 'night', 'ninny', 'ninth', 'nippy', 'nitro', 'noble', 'nobly', 'nodal', 'noise', 'noisy', 'nomad', 'nonce', 'noose', 'nopal', 'north', 'nosey', 'notch', 'noted', 'novel', 'nubby', 'nudge', 'nurse', 'nutty', 'nylon', 'nymph', 'oaken', 'oasis', 'obeah', 'obese', 'occur', 'ocean', 'ocher', 'ochre', 'octet', 'odder', 'oddly', 'offal', 'offer', 'often', 'ogler', 'oiled', 'okapi', 'olden', 'oldie', 'olive', 'onion', 'onset', 'ontic', 'oomph', 'opera', 'opine', 'opium', 'optic', 'orang', 'orbit', 'order', 'organ', 'other', 'otter', 'ought', 'outdo', 'outer', 'outre', 'ovary', 'overt', 'ovoid', 'ovule', 'owing', 'owlet', 'owned', 'owner', 'oxbow', 'oxide', 'ozone', 'paddy', 'paean', 'pagan', 'pager', 'paint', 'palmy', 'palsy', 'panda', 'panel', 'panga', 'panic', 'pansy', 'panty', 'papal', 'paper', 'parch', 'parka', 'parry', 'parse', 'party', 'pasha', 'passe', 'pasta', 'paste', 'pasty', 'patch', 'patio', 'pause', 'paved', 'paver', 'payee', 'payer', 'payor', 'peace', 'peach', 'pearl', 'peaty', 'pecan', 'pedal', 'peeve', 'penal', 'penis', 'penne', 'peppy', 'perch', 'peril', 'perky', 'pesky', 'petal', 'petri', 'petty', 'phage', 'phase', 'phial', 'phlox', 'phone', 'phony', 'piano', 'picky', 'piece', 'piety', 'piggy', 'piker', 'pilaf', 'pilot', 'pinch', 'pinko', 'pinna', 'pinon', 'pious', 'piped', 'pique', 'piste', 'pitch', 'pithy', 'piton', 'pivot', 'pixel', 'pixie', 'pizza', 'place', 'plage', 'plaid', 'plain', 'plait', 'plane', 'plank', 'plant', 'plasm', 'plate', 'plead', 'pleat', 'plebe', 'plena', 'plink', 'plonk', 'pluck', 'plumb', 'plume', 'plump', 'plunk', 'plush', 'poach', 'point', 'poise', 'poker', 'polar', 'polio', 'polis', 'polka', 'polyp', 'pooch', 'poofy', 'poopy', 'poppy', 'porch', 'porky', 'porno', 'posed', 'poser', 'posit', 'posse', 'potty', 'pouch', 'pound', 'pouty', 'power', 'prang', 'prank', 'prawn', 'preen', 'press', 'price', 'prick', 'pricy', 'pride', 'prima', 'prime', 'primo', 'primp', 'print', 'prion', 'prior', 'prise', 'prism', 'privy', 'prize', 'probe', 'prole', 'promo', 'prone', 'prong', 'proof', 'prose', 'proud', 'prove', 'prowl', 'proxy', 'prude', 'prune', 'psoas', 'psych', 'pubic', 'pubis', 'pudgy', 'puffy', 'pulpy', 'pulse', 'punch', 'punky', 'pupal', 'pupil', 'puppy', 'pured', 'puree', 'purge', 'purse', 'purty', 'pushy', 'pussy', 'putty', 'pygmy', 'pylon', 'quack', 'quaff', 'quail', 'quake', 'quale', 'qualm', 'quant', 'quark', 'quash', 'quasi', 'qubit', 'queen', 'queer', 'quell', 'query', 'quest', 'queue', 'quick', 'quiet', 'quill', 'quilt', 'quint', 'quire', 'quirk', 'quirt', 'quite', 'quits', 'quota', 'quote', 'rabbi', 'rabid', 'racer', 'radar', 'radio', 'radon', 'raggy', 'rainy', 'raise', 'raita', 'raked', 'rally', 'ramie', 'ranch', 'randy', 'range', 'rangy', 'raped', 'rapid', 'raspy', 'rated', 'rater', 'ratio', 'ratty', 'ravel', 'raver', 'rayon', 'razor', 'reach', 'react', 'ready', 'realm', 'rearm', 'rebel', 'rebus', 'rebut', 'recap', 'recon', 'recto', 'recur', 'redly', 'redox', 'reedy', 'refer', 'refit', 'regal', 'rehab', 'reify', 'reign', 'reiki', 'relax', 'relay', 'relic', 'remit', 'remix', 'renal', 'renew', 'repay', 'repel', 'reply', 'repot', 'rerun', 'reset', 'resin', 'retch', 'retro', 'retry', 'reuse', 'revel', 'revue', 'rhino', 'rhyme', 'ricer', 'ricin', 'rider', 'ridge', 'rifle', 'right', 'rigid', 'rigor', 'riled', 'rille', 'rinse', 'ripen', 'risen', 'riser', 'risky', 'ritzy', 'rival', 'riven', 'river', 'rivet', 'roach', 'roast', 'robed', 'robot', 'rocky', 'rodeo', 'rogue', 'roily', 'roman', 'roomy', 'roost', 'rooty', 'roped', 'ropey', 'rosin', 'rotor', 'rouge', 'rough', 'round', 'rouse', 'roust', 'route', 'rover', 'rowan', 'rowdy', 'rower', 'royal', 'ruddy', 'rugby', 'ruled', 'ruler', 'rumba', 'rumen', 'rummy', 'rumor', 'runic', 'runny', 'runty', 'rural', 'rusty', 'saber', 'sable', 'sabot', 'sadhu', 'sadly', 'saggy', 'salad', 'sales', 'sally', 'salon', 'salsa', 'salty', 'salve', 'salvo', 'samba', 'sambo', 'sandy', 'sappy', 'sarin', 'sassy', 'satay', 'sated', 'satin', 'satyr', 'sauce', 'saucy', 'sauna', 'saved', 'saver', 'savin', 'savor', 'savvy', 'sawed', 'scald', 'scale', 'scalp', 'scaly', 'scamp', 'scant', 'scape', 'scare', 'scarf', 'scarp', 'scary', 'scaup', 'scene', 'scent', 'schmo', 'scoff', 'scold', 'scone', 'scoop', 'scoot', 'scope', 'score', 'scorn', 'scots', 'scour', 'scout', 'scowl', 'scram', 'scrap', 'scree', 'screw', 'scrim', 'scrip', 'scrod', 'scrub', 'scrum', 'scuba', 'scuff', 'scull', 'seamy', 'sebum', 'sedan', 'sedge', 'sedum', 'seedy', 'segue', 'seine', 'seize', 'semen', 'sense', 'sepal', 'sepia', 'sepoy', 'septa', 'serge', 'serif', '

In [27]:
valid_guesses_csv = pd.DataFrame(valid_guesses, columns=["word"])
valid_guesses_csv.to_csv("valid_guesses_words.csv")
valid_solutions_csv = pd.DataFrame(valid_solutions, columns=["word"])
valid_solutions_csv.to_csv("valid_solutions_words.csv")

In [38]:
data = pd.read_excel("COCA60000FULL.xlsx")
data["word"] = data["word"].str.replace(' ', '')

data_selected = data[data["word"].str.len() == 5]
word_frequency = data_selected.sort_values(by="TOTAL", axis=0, ascending=True)
word_frequency

,RANK #,PoS,word,TOTAL,SPOKEN,FICTION,MAGAZINE,NEWSPAPER,ACADEMIC
57873,57875,J,unhip,18,0,7,4,6,1
59267,59269,R,roily,19,0,11,7,0,1
58747,58749,J,topsy,19,4,10,2,1,2
58806,58808,N,shoat,19,0,14,2,2,1
58818,58820,J,homed,19,0,10,4,0,5
...,...,...,...,...,...,...,...,...,...
55,56,V,think,838695,423892,193081,88312,93525,39885
52,53,E,there,846483,301556,155571,135904,139865,113587
45,46,I,about,952604,328762,178533,163092,163636,118581
40,41,V,would,1000182,251284,257792,166384,178690,146032
35,36,A,their,1170105,184917,176141,250636,232098,326313

In [41]:
word_frequency["frequency"] = word_frequency["TOTAL"] / word_frequency["TOTAL"].sum()
word_frequency

,RANK #,PoS,word,TOTAL,SPOKEN,FICTION,MAGAZINE,NEWSPAPER,ACADEMIC,frequency
57873,57875,J,unhip,18,0,7,4,6,1,4.164350e-07
59267,59269,R,roily,19,0,11,7,0,1,4.395703e-07
58747,58749,J,topsy,19,4,10,2,1,2,4.395703e-07
58806,58808,N,shoat,19,0,14,2,2,1,4.395703e-07
58818,58820,J,homed,19,0,10,4,0,5,4.395703e-07
...,...,...,...,...,...,...,...,...,...,...
55,56,V,think,838695,423892,193081,88312,93525,39885,1.940344e-02
52,53,E,there,846483,301556,155571,135904,139865,113587,1.958362e-02
45,46,I,about,952604,328762,178533,163092,163636,118581,2.203876e-02
40,41,V,would,1000182,251284,257792,166384,178690,146032,2.313949e-02
35,36,A,their,1170105,184917,176141,250636,232098,326313,2.707070e-02

In [28]:
# 状态列表与状态码相互转换
def status_transform2number(status=[0, 0, 0, 0, 0]):
    res = 0
    a = 1
    for i in status:
        res += a * i
        a = a * 3
    return res

def number_transform2status(number=0):
    res = []
    for i in range(5):
        res.append(number % 3)
        number //= 3
    return res

# 生成合法的状态排列
def generate_status():
    res = []
    for i in range(243):
        cur = []
        x = i
        for j in range(5):
            cur.append(x % 3)
            x //= 3
        res.append(cur)
        
    return res

In [29]:
# 对猜测答案与正确答案之间进行验证
# 状态0代表完全错误，1代表字母正确且位置错误，2代表字母和位置都正确
def validation(guess, solution):
    result = [0, 0, 0, 0, 0]
    guess_list = list(guess)
    solution_list = list(solution)
    solution_letter_remainder = []
    
    for i in range(5):
        if guess_list[i] == solution_list[i]:
            result[i] = 2
        else:
            solution_letter_remainder.append(solution_list[i])
    
    for i in range(5):
        if result[i] == 2:
            continue
        for ch in solution_letter_remainder:
            if guess[i] == ch:
                result[i] = 1
                solution_letter_remainder.remove(ch)
                break
    
    return result

print( validation("grape", "hello") )
print( validation("heart", "hello") )
print( validation("hello", "hello") )

[0, 0, 0, 0, 1]
[2, 2, 0, 0, 0]
[2, 2, 2, 2, 2]

In [30]:
# 在单词集中找出符合要求的所有单词
def get_legal_words(guess, status, valid_words):
    legal_words = []
    
    for word in valid_words:
        result = validation(guess, word)
        flag = True
        
        for i in range(5):
            if status[i] != result[i]:
                flag = False
                break
                
        if flag == True:
            legal_words.append(word)
    
    return legal_words


print( get_legal_words("hello", [2, 2, 0, 0, 0], valid_solutions) )
print( get_legal_words("hello", [2, 2, 0, 0, 1], valid_solutions) )
print( get_legal_words("hello", [2, 2, 0, 0, 1], valid_guesses) )

['heart', 'heavy']
[]
['heron']

In [42]:
# 计算信息量（信息熵）
def Entropy(p):
    if p == 0 or p == 1:
        return 0.0
    return - p * np.log(p) - (1.0 - p) * np.log(1.0 - p)


# 统计单词集中符合要求的所有单词的数量
def get_legal_words_cnt(guess, status, valid_words):
    legal_words = get_legal_words(guess, status, valid_words)
    return len(legal_words)


# 统计单词集中符合要求的所有单词的信息量（信息熵）
def get_legal_words_entropy(guess, status, valid_words):
    if len(valid_words) == 0:
        return 0.0
    p = get_legal_words_cnt(guess, status, valid_words) / len(valid_words)
    
    if p == 0 or p == 1:
        return 0.0
    entropy = Entropy(p)
    
    return entropy

# print( get_legal_words_entropy("hello", [2, 2, 0, 0, 0]) )
# print( get_legal_words_entropy("hello", [0, 0, 0, 0, 1]) )


# 计算总信息量（信息熵）
def get_legal_words_total_entropy(guess, last_status, valid_words):
    total_status = generate_status()
    total_entropy = 0
    for status in total_status:
        total_entropy += get_legal_words_entropy(guess, status, valid_words)
    return total_entropy

# print( get_legal_words_total_entropy("hello") )


# 获取词汇频率
def get_word_frequency(guess):
    result = word_frequency[ word_frequency["word"] == guess ]
    weight = result["frequency"].tolist()
    res = sum(weight)
    
    # print(res)
    return res
    
print( get_word_frequency("hello") )

0.0004243472410662262

In [47]:
guess_legal_words_data = []
guess_legal_words_metrics_data = []

for guess in valid_guesses[0:0]:
    total_entropy = 0
    word_frequency = get_word_frequency(guess)
    # print(guess)
    
    for number in range(243):
        legal_words = get_legal_words(guess, number_transform2status(number), valid_solutions)
        len_of_legal_words = len(legal_words)
        if len_of_legal_words == 0:
            continue
        guess_legal_words_data.append([guess, number, legal_words, len_of_legal_words])
        total_entropy += Entropy(len_of_legal_words / valid_solutions_cnt)
    
    guess_legal_words_metrics_data.append([guess, total_entropy, word_frequency])

In [48]:
guess_legal_words_data = pd.DataFrame(guess_legal_words_data, columns=["guess", "number", "legal_words", "len_of_legal_words"], dtype=int)
guess_legal_words_data.to_csv("guess_legal_words_data(valid_solutions).csv")
guess_legal_words_metrics_data = pd.DataFrame(guess_legal_words_metrics_data, columns=["guess", "total_entropy", "word_frequency"], dtype=float)
guess_legal_words_metrics_data.to_csv("guess_legal_words_metrics_data(valid_solutions).csv")

In [ ]:
guess_legal_words_data = []
# guess_legal_words_metrics_data = []

for guess in valid_guesses:
    # total_entropy = 0
    # words_frequency = get_word_frequency(guess)
    print(guess)
    
    for number in range(243):
        legal_words = get_legal_words(guess, number_transform2status(number), valid_guesses)
        len_of_legal_words = len(legal_words)
        if len_of_legal_words == 0:
            continue
        guess_legal_words_data.append([guess, number, legal_words, len_of_legal_words])
        # total_entropy += Entropy(len_of_legal_words / valid_guesses_cnt)
    
    # guess_legal_words_metrics_data.append([guess, total_entropy, words_frequency])


guess_legal_words_data = pd.DataFrame(guess_legal_words_data, columns=["guess", "number", "legal_words", "len_of_legal_words"], dtype=int)
guess_legal_words_data.to_csv("problem2_model_guess_legal_words_data(valid_guesses).csv")
# guess_legal_words_metrics_data = pd.DataFrame(guess_legal_words_metrics_data, columns=["guess", "total_entropy", "words_frequency"], dtype=float)
# guess_legal_words_metrics_data.to_csv("problem2_model_guess_legal_words_metrics_data(valid_solutions).csv")

aback
abase
abash
abate
abaya
abbot
abhor
abide
abode
abort
about
above
abuse
abyss
ackee
acorn
acrid
actin
actor
acute
adage
adapt
added
adder
addle
adept
adieu
adios
adman
admin
admit
adobe
adobo
adopt
adore
adorn
adult
aegis
aerie
affix
afire
afoot
afore
after
again
agape
agave
agent
aggro
agile
aging
aglow
agony
agora
agree
ahead
ahold
aided
aioli
aired
aisle
alarm
album
alder
alert
algae
algal
alias
alibi
alien
align
alike
alive
alkyd
allay
alley
allot
allow
alloy
aloft
alone
along
aloof
aloud
alpha
altar
alter
amass
amaze
amber
ambit
amble
amend
amine
amino
amiss
amity
amnio
among
amour
ample
amply
amuse
ancho
angel
anger
angle
anglo
angry
angst
anima
anime
anion
anise
ankle
annal
annex
annoy
annul
anode
anole
antic
antsy
anvil
aorta
apace
apart
aphid
apnea
apple
apply
apron
aptly
ardor
areal
arena
argon
argot
argue
arise
armed
armor
aroma
array
arrow
arson
artsy
ashen
aside
askew
aspic
assay
asset
aster
astir
atman
atoll
atone
attar
attic
audio
audit
auger
aught
augur
aunty